// Golden City Ward — Dasmariñas Philippines Stake
export const CALLING_POSITIONS: { group: string; positions: string[] }[] = [
  {
    group: 'Bishopric',
    positions: [
      'Bishop',
      'Bishopric First Counselor',
      'Bishopric Second Counselor',
      'Ward Executive Secretary',
      'Ward Assistant Executive Secretary',
      'Ward Clerk',
      'Ward Assistant Clerk',
      'Ward Assistant Clerk--Membership',
      'Ward Assistant Clerk--Finance',
    ],
  },
  {
    group: 'Elders Quorum',
    positions: [
      'Elders Quorum President',
      'Elders Quorum First Counselor',
      'Elders Quorum Second Counselor',
      'Elders Quorum Secretary',
      'Elders Quorum Assistant Secretary',
      'Elders Quorum Teacher',
      'Elders Quorum Ministering Secretary',
      'Elders Quorum Activity Coordinator',
      'Elders Quorum Assistant Activity Coordinator',
      'Elders Quorum Activity Committee Member',
      'Elders Quorum Service Coordinator',
      'Elders Quorum Assistant Service Coordinator',
      'Elders Quorum Service Committee Member',
    ],
  },
  {
    group: 'Relief Society',
    positions: [
      'Relief Society President',
      'Relief Society First Counselor',
      'Relief Society Second Counselor',
      'Relief Society Secretary',
      'Relief Society Assistant Secretary',
      'Relief Society Teacher',
      'Relief Society Ministering Secretary',
      'Relief Society Activity Coordinator',
      'Relief Society Assistant Activity Coordinator',
      'Relief Society Activity Committee Member',
      'Relief Society Music Leader',
      'Relief Society Pianist',
      'Relief Society Service Coordinator',
      'Relief Society Assistant Service Coordinator',
      'Relief Society Service Committee Member',
    ],
  },
  {
    group: 'Aaronic Priesthood',
    positions: [
      'Priests Quorum President',
      'Priests Quorum First Assistant',
      'Priests Quorum Second Assistant',
      'Priests Quorum Secretary',
      'Priests Quorum Adviser',
      'Priests Quorum Specialist',
      'Teachers Quorum President',
      'Teachers Quorum First Counselor',
      'Teachers Quorum Second Counselor',
      'Teachers Quorum Secretary',
      'Teachers Quorum Adviser',
      'Teachers Quorum Specialist',
      'Deacons Quorum President',
      'Deacons Quorum First Counselor',
      'Deacons Quorum Second Counselor',
      'Deacons Quorum Secretary',
      'Deacons Quorum Adviser',
      'Deacons Quorum Specialist',
      'Aaronic Priesthood Quorums Specialist',
      'Aaronic Priesthood Quorums Specialist - Camp Director',
      'Aaronic Priesthood Quorums Specialist - Assistant Camp Director',
      'Young Men Stake Youth Committee Member',
      'Young Men Specialist - Sports',
      'Young Men Specialist - Sports Assistant',
    ],
  },
  {
    group: 'Young Women',
    positions: [
      'Young Women President',
      'Young Women First Counselor',
      'Young Women Second Counselor',
      'Young Women Secretary',
      'Young Women Specialist',
      'Young Women Specialist - Activities',
      'Young Women Specialist - Camp Director',
      'Young Women Specialist - Assistant Camp Director',
      'Young Women Specialist - Sports',
      'Young Women Specialist - Sports Assistant',
      'Young Women Stake Youth Committee',
      'Young Women Class President',
      'Young Women Class First Counselor',
      'Young Women Class Second Counselor',
      'Young Women Class Secretary',
      'Young Women Class Adviser',
    ],
  },
  {
    group: 'Sunday School',
    positions: [
      'Sunday School President',
      'Sunday School First Counselor',
      'Sunday School Second Counselor',
      'Sunday School Secretary',
      'Sunday School Teacher',
    ],
  },
  {
    group: 'Primary',
    positions: [
      'Primary President',
      'Primary First Counselor',
      'Primary Second Counselor',
      'Primary Secretary',
      'Primary Pianist',
      'Primary Music Leader',
      'Primary Teacher',
      'Nursery Leader',
      'Valiant Activities Leader',
      'Resource Center Specialist',
    ],
  },
  {
    group: 'Ward Missionaries',
    positions: [
      'Ward Mission Leader',
      'Assistant Ward Mission Leader',
      'Ward Missionary',
    ],
  },
  {
    group: 'Temple and Family History',
    positions: [
      'Ward Temple and Family History Leader',
      'Ward Temple and Family History Consultant',
      'Indexing Worker',
    ],
  },
  {
    group: 'Young Single Adult',
    positions: [
      'Young Single Adult Leader',
      'Young Single Adult Adviser',
      'Young Single Adult Committee Chair',
      'Young Single Adult Committee Member',
      'Relief Society Adviser to Young Single Adult Sisters',
    ],
  },
  {
    group: 'Music',
    positions: [
      'Accompanist',
      'Choir Accompanist',
      'Choir Director',
      'Music Adviser',
      'Music Coordinator',
      'Music Leader',
      'Priesthood Music Director',
      'Priesthood Pianist or Organist',
    ],
  },
  {
    group: 'Welfare and Self-Reliance',
    positions: [
      'Welfare and Self-Reliance Specialist',
      'Self-Reliance Group Facilitator',
      'Disability Activity Leader',
      'Disability Specialist',
    ],
  },
  {
    group: 'Other',
    positions: [
      'Building Representative',
      'Email Communication Specialist',
      'FSY Conferences Representative',
      'History Specialist',
      'Magazine Representative',
      'Technology Specialist',
      'Ward/Branch Interpreter',
    ],
  },
]

export const ALL_CALLING_POSITIONS = CALLING_POSITIONS
  .flatMap((g) => g.positions)
  .sort((a, b) => a.localeCompare(b))
