INSERT INTO members (
  preferred_name,
  address_street1,
  address_street2,
  address_city
) VALUES
('Torres, Gigi Tambis', 'Armstrong Village', NULL, 'Dasmariñas City'),
('Traquena, Yvan Kendric Gozon', 'Block 63 Lot 23 Golden City Dasmariñas', 'Phase I', 'Dasmariñas'),
('Traqueña, Christine Joy Guzon', 'Phase 1, Block 25, Lot 28', 'Golden City Subd. Dasma - 1', 'Dasmariñas City'),
('Trinio, Erly Cabayao', 'Phase 4, Paliparan Site', NULL, 'Dasmariñas City'),
('Tubac, Judith Halop', 'PH-5, Dasma 1 Golden City', NULL, 'Dasmariñas City'),
('Tulang, Khian Jhamier', 'DASMARIÑAS', NULL, 'TRECE MARTIRES CITY'),
('Tutisora, Jellian Rose', 'Blk 31 Lot 31', 'Camella Homes Myrtle St.', 'Dasmarinas City'),
('Umbao, Johnny Palino', 'phase 6, block 39, lot 8', 'Golden City', 'Dasmariñas'),
('Valdez, Chonalyn Romano', 'Block 159 Lot 5 Phase 4-A Paliparan III', NULL, 'Dasmariñas'),
('Vejerano, David Andrei Cadiz', 'Lot 25 Blk 1 San Marino Heights Salawag', NULL, 'Dasmariñas City'),
('Vejerano, Herma Acob Cadiz', 'Blk. 1 Lot 25, San Marino Heights', 'Salawag', 'Dasmarinas, City'),
('Vejerano, Ivana Jae Cadiz', 'Blk. 1 Lot 25, San Marino Heights', 'Salawag', 'Dasmarinas, City'),
('Victoriano, Clarence', 'Blk 41, Lt 22 Ph 1', NULL, 'Dasmarinas'),
('Victoriano, Clarise', 'Blk 41, Lt 22 Ph 1', NULL, 'Dasmarinas'),
('Victoriano, Rose Camillie Joy', 'Blk 41, Lt 22 Ph 1', NULL, 'Dasmarinas'),
('Villa, Jonas Ocdol', 'Blk 27 Lot 34, California St.', 'San Marino City, Brgy Salang', 'Dasmarinas, City'),
('Villa, Joshua Ocdol', 'Blk 27 Lot 34, California St.', 'San Marino City, Brgy Salang', 'Dasmarinas, City'),
('Villa, Moises Ocdol', 'Blk 27 Lot 34, California St.', 'San Marino City, Brgy Salang', 'Dasmarinas, City'),
('Villa, Rammel Ocdol', 'Blk 27 Lot 34, California St.', 'San Marino City, Brgy Salang', 'Dasmarinas, City'),
('Villa, Ramon Millan Jr.', 'Blk 27 Lot 34, California St.', 'San Marino City, Brgy Salang', 'Dasmarinas, City'),
('Villa, Ruth Ocdol', 'Blk 27 Lot 34, California St.', 'San Marino City, Brgy Salang', 'Dasmarinas, City'),
('Villabito, Mary Queen Marcelo', '16 DASMA 3 AVENUE', NULL, 'DASMARIÑAS'),
('Villabito, Meriam', '16 DASMA 3 AVENUE', NULL, 'DASMARIÑAS'),
('Villamor, Nathaniel Clavel', 'Sitio Malabon', NULL, 'Dasmariñas City'),
('Villanueva, Emelda Cojuangco', 'B23 L14 P3 Mabuhay city Subd.', NULL, 'Dasmariñas City'),
('Villanueva, Mark Rath Cortez', 'Block 57 Lot 10 Phase 1', 'Mabuhay', 'Dasmariñas'),
('Villar, Jennifer', 'Nia Road', NULL, 'Dsamarinas'),
('Villar, Kobe Anog', 'Nia Road', NULL, 'Dsamarinas'),
('Villar, Kyrie Anog', 'Nia Road', NULL, 'Dsamarinas'),
('Villar, Precious Mary Lorenzo', 'Nia Road', NULL, 'Dsamarinas'),
('Viña, Renee Fortes Devera', 'Blk.33 Lot 09 Fierway View Subd', NULL, 'Dasmariñas City'),
('Viñas, Clark Jacob Candido', '1 MICHIGAN STREET', NULL, 'DASMARIÑAS'),
('Viñas, Lea Olie Candido', '1 MICHIGAN STREET', NULL, 'DASMARIÑAS'),
('Viñas, Mheljahp Mojedo', '1 MICHIGAN STREET', NULL, 'DASMARIÑAS'),
('Yusalan, Kelvin Salinas', 'B6 L25 Bangladesh Street', 'San Marino City, Salawag', 'Dasmariñas'),
('Zamaro, Rizalino Nudalo', 'Blk 58 Lot 13 Mabuhay Homes, Golden City', NULL, 'Dasmariñas City'),
('Zamora, Charles Jerck Falceso', 'Block 65, Lot 5 Phase 4 Mabuhay City', NULL, 'Dasmarinas City'),
('Zorilla, Danilo Opinion', 'Blk 08 Lot 27 Phase - 9 Golden City Subd', 'Dasma - 4 Brgy. Salawag', 'Dasmariñas City'),
('Zorilla, Julie Toblas Ofrancia', 'Blk 08 Lot 27 Phase - 9 Golden City Subd', 'Dasma - 4 Brgy. Salawag', 'Dasmariñas City');
